name: WebApp Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install FTP client
        run: sudo apt-get install -y lftp
        
      - name: Deploy to FTP server
        run: |
          lftp -c "open -u ${{ secrets.DEPLPOY_USERNAME }},${{ secrets.DEPLOY_PASSWORD }} ${{ secrets.FTP_SERVER }}; set ssl:verify-certificate no; mirror --exclude-glob '__pycache__/*' --exclude-glob 'venv/*' --exclude-glob '.gitignore' -R --reverse --verbose ./web ./web"
      
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Install SSH pass
        run: sudo apt-get install -y sshpass

      - name: Install requirements
        run: sshpass -p ${{ secrets.DEPLOY_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.SSH_SERVER }} 'cd tr2_projeto/web && pip install -r requirements.txt'
